<?php
// @codingStandardsIgnoreFile

/**
 * @var Infortis\Base\Block\Html\Header\Logo $block
 */
?>
<?php
    $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
?>
<?php if ($block->isHomePage()):?>
    <h1 class="logo">
        <a href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
            <strong><?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?></strong>
            <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
                 alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
                 <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                 <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
            />
        </a>
    </h1>
<?php else: ?>
        <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
            <strong><?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?></strong>
            <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
                 alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
                 <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                 <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
            />
        </a>
<?php endif?>




<!-- MAIN -->
<style>

/*MAIN*/
.js-left-banner{
    width: 45%;
    float: left;
    padding: 40px;
    box-sizing: border-box;
    display: none;
}
.main-top-container .js-left-banner{
display: block;
    }
    .js-conditions{
        display: none;
        clear: both;
        padding: 40px 0;
        box-sizing: border-box;
        overflow: hidden;
    }
    .main-top-container .js-conditions{
        display: block;
    }
.slideshow-wrapper-additional{
    width: 49%;
    float: right;
}
.slideshow-wrapper-additional img{
    max-width: 600px;
}
.slideshow-wrapper-additional .owl-item{
    max-width: 100%;
}
.owl-buttons{
    display: none;
}
.js-left-banner{
    width: 45%;
    float: left;
    padding: 40px;
    box-sizing: border-box;
}
.HomeCarousel-navItem-12D h3 {
    padding-top: 0;
    margin-bottom: 5px;
    /*font-family: Apercu;*/
}
.HomeCarousel-navItem-12D:before {
    display: block;
    position: absolute;
    top: 2px;
    left: 0;
    z-index: 1;
    width: 33px;
    height: 33px;
    line-height: 33px;
    border-radius: 50%;
    background: #476ce1;
    content: counter(my-awesome-counter);
    text-align: center;
    /*font-family: Apercu;*/
    font-weight: 300;
    color: #fff;
}
@media only screen and (min-width: 850px){
    .HomeCarousel-navItem-12D:before {
    position: relative;
    width: 52px;
    height: 52px;
    line-height: 52px;
    font-size: 22px;
   
    margin-bottom: 40px;
    background: #fff;
    color: #020134;
    border: 1px solid #d8e5e8;
    -webkit-animation-name: HomeCarousel-carousel-counter-3sQ;
    animation-name: HomeCarousel-carousel-counter-3sQ;
    -webkit-animation-duration: 5s;
    animation-duration: 5s;
    -webkit-animation-fill-mode: forwards;
    animation-fill-mode: forwards;
    -webkit-animation-iteration-count: 1;
    animation-iteration-count: 1;
}
    .HomeCarousel-navItem-12D h3 {
    font-size: 22px !important;
    line-height: 27px;
}
  .HomeCarousel-infoInner-1SG {
    max-width: 440px;
}  
}
.HomeCarousel-slideHeading-1-9 em {
    font-style: normal;
    color: #476ce1;
}
.HomeCarousel-info-1ug h1 {
    margin-bottom: 1rem;
    padding-top: 0;
    font-weight: 300;
    -webkit-font-smoothing: antialiased;
}
.HomeCarousel-nav-2Ty {
    position: relative;
    list-style: none;
    margin-left: 0;
    margin-bottom: 0;
    counter-reset: my-awesome-counter;
    padding-top: 30px;
    padding-bottom: 30px;
    border-bottom: 1px solid #d8e5e8;
    overflow-x: hidden;
}
.HomeCarousel-navItem-12D {
    position: relative;
    /*padding-left: 60px;*/
    padding: 40px;
    box-sizing: border-box;
    counter-increment: my-awesome-counter;
    margin-bottom: 30px;
}

@media only screen and (min-width: 850px){

.HomeCarousel-nav-2Ty {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    padding-top: 0;
    padding-bottom: 60px;
    margin-top: -26px;
        justify-content: space-around;
}
}
@media only screen and (min-width: 850px){

.HomeCarousel-navItem-12D {
    padding-left: 0;
    margin-bottom: 0;
    width: calc(33.3333% - 13.33333px);
}

}
@media only screen and (min-width: 1000px){
.HomeCarousel-nav-2Ty {
    grid-column-gap: 80px;
}
.HomeCarousel-navItem-12D {
    width: calc(33.3333% - 53.33333px);
}
}

@keyframes conditionsLineA{
  0%  { width: 0%; }
  100% { width: 35%; }
}
@keyframes conditionsLineB{
  0%  { width: 35%; }
  100% { width: 73%; }
}
@keyframes conditionsLineC{
  0%  { width: 73%; }
  100% { width: 105%; }
}

.js-line-cont{
    padding: 0 50px;
    box-sizing: border-box;
}
.anim-conditionsLine1{
    animation: conditionsLineA;

}
.anim-conditionsLine2{
    width: 35%;
    animation: conditionsLineB;

}
.anim-conditionsLine3{
    width: 73%;
    animation: conditionsLineC;

}
.anim-conditionsLine{
    margin-top: 50px;
    margin-bottom: 50px;
    width: 0;
    height: 2px;
      background-color: #476ce1;
      margin-bottom: -70px;

    animation-duration: 7.9s;
    animation-timing-function: linear;
    animation-fill-mode: forwards;

}
.HomeCarousel-navItem-12D.conditions_act-circle:before{
    color: #fff;
      background-color: #476ce1;
      border: none;

}
.js-btn-account{
    background-color: inherit;
    font-weight: normal;
    font-size: inherit;
    color: #333;
}
.js-btn-account:hover{
    color: #fff !important;
    background-color: #30a5ff;
}


/*li:nth-child(2) .nav-panel{
    display: block !important;
    border: 0 !important;
    box-shadow: none !important;;;
}
.sticky-header .sticky-container{
    position: relative !important;
}*/

a:hover{
    color: #20247d;
}
#mainmenu>ul>li:hover>.megamenu-wrap>.nav-panel{
display: block;
}
#mainmenu>ul>li>.megamenu-wrap>.nav-panel{
        height: 330px !important;
        padding: 30px !important;
    overflow-x: hidden;
    overflow-y: scroll;
        max-height: 50vh;
        width: 75% !important;

}
#mainmenu>ul>li>.nav-panel.megamenu-wrap{
    padding: 30px;
    margin-top: 20px;
    overflow: hidden !important;
     -webkit-box-shadow: 0 0 20px 5px rgba(0,0,0,.5) !important;
    box-shadow: 0 0 20px 5px rgba(0,0,0,.5) !important;
  position: absolute !important;
  min-height: 330px;
}
.nav-panel{
    width: 100% !important;
    left: 0 !important;
        border: 0 !important;
        box-shadow: none !important;
}
.nav-panel .nav-panel{
    height: auto !important;
    overflow: hidden;
    padding: 0 !important;
}
.nav-panel .caret{
    display: none !important;
}
.nav-panel li.level1{
width: 30%;
float: left;
margin-bottom: 40px;
}
.nav-panel li.level2{
/*display: inline-block;*/
margin-right: 15px;
display: none;
}
.nav-panel li.level2:nth-child(1),
.nav-panel li.level2:nth-child(2),
.nav-panel li.level2:nth-child(3){
display: inline-block;
}
.nav-panel li.level1>a{
font-size: 15px;
/*font-size: 18px;*/

margin-bottom: 10px;
cursor: auto;
font-weight: bold;
padding-left: 0 !important;
}
.nav-panel li.level2>a{
font-size: 14px;
/*font-size: 15px;*/

padding-left: 0 !important;

}
ul.nav-panel li a:hover{
text-decoration: underline;
color: #20247d !important;

}
ul.nav-panel li.level1 a:hover{
text-decoration: none;
}
.nav-panel li ul{
    display: block !important;
    opacity: 1 !important;
    position: static !important;
}
ul.nav-panel.level2{
    display: none !important;
}
.megamenu-aside{
    display: none;
}
.megamenu-wrap .megamenu-aside{
    display: block;
    width: 25%;
    height: 100%;
    background-color: #3035ba;
    position: absolute;
    top: 0;
    box-sizing: border-box;
    right: 0;
    /*z-index: 100;*/
    padding: 30px;

}
.megamenu-wrap .megamenu-aside h3{
color: #fff;
font-size: 18px;
}
</style>
<!-- left banner -->
<div class="js-left-banner">
    <div class="HomeCarousel-info-1ug">
    <div class="HomeCarousel-infoInner-1SG">
    <h1 class="HomeCarousel-slideHeading-1-9">
    Medicine delivered <em>discreetly</em> to your door</h1>
    <p>Get the same genuine medicines delivered to your door in 
    as little as 24 hours as you would from your GP - without the wait.</p>
    </div>
    </div>
    </div>

<!-- conditions -->
<div class="js-conditions">
<div class="js-line-cont"><div class="js-line"></div></div>

<ol class="HomeCarousel-nav-2Ty"><li class="HomeCarousel-navItem-12D "><h3>Choose your treatment</h3><p>Sit back, relax and choose your one-off or subscription of medication on any device from anywhere.</p></li><li class="HomeCarousel-navItem-12D"><h3>Complete a consultation</h3><p>With complete privacy and confidentiality your form is checked by our partner GMC UK Regulated doctor and then dispensed by UK Meds Pharmacy</p></li><li class="HomeCarousel-navItem-12D"><h3>Receive your delivery</h3><p>With same day service in parts of the UK, you can have your treatment delivery discreetly within hours.</p></li></ol>
</div>
<!-- megamenu right aside -->
<aside class="megamenu-aside">
    <h3>Related Help & Advice</h3>

</aside>


<script>
    //<![CDATA[

requirejs(['jquery'], function(jQuery) {


    jQuery(function($) {

        // for home page
        if($('body').hasClass('cms-index-index')){
// slider
var leftBanner = $('.js-left-banner');
var slider = $('.slideshow-wrapper-additional');
var wrapper = $('.main-top-container');
wrapper.addClass('container');
slider.before(leftBanner);

var conditions = $('.js-conditions');
wrapper.append(conditions);
}

// header account links
                        function showAccountForm(){
                            console.log('showAccountForm');
    // var that = $(this);

    
}
$('#header-account').find('a').each(function(){


    var that = $(this);
    var text = $.trim(that.text());
    var accountText = 'my account';
    var createAccountText = 'create an account';
    text = text.toLowerCase();
    if(text == accountText){

that.hide();
var url = that.attr('href');
console.log(url);
that.after('<button class="js-btn-account">'+that.text()+'</button>');

var but = $('.js-btn-account');
but.on('click', function(){
    showAccountForm();
})
    }
    if(text == createAccountText){
        that.hide();
    }
});

// megamenu
var megamenuUL = $('#mainmenu>ul>li>.nav-panel');
var megamenuULclass = megamenuUL.attr('class');
megamenuUL.wrap('<div class="'+megamenuULclass+' megamenu-wrap"></div');
var megamenuCont = $('.megamenu-wrap');
var megamenuAside = $('.megamenu-aside');
megamenuCont.append(megamenuAside);


    });
    });


</script>
